### PR TITLE
Database schema changes

### PR DESCRIPTION
**Pull request by mbabker**
- Adds unique index to the `#__issues` table on issue number and project ID
- Adds cascade operations to the `#__issue_category_map` table's foreign key to the `#__issues` table

### CODE REVIEW

**Comment by b2z** [comment]
So I suppose I cannot test it, right?

**Comment by mbabker** [comment]
You could do it in a local database.  If you delete a record from the `#__issues` table, the associated rows in the `#__issue_category_map` table should also delete with this patch (right now MySQL causes the delete to fail due to foreign key constraints).

For the unique index, apply it then try adding a record that has the same project ID and issue number as an existing row, it should fail.  But you should be able to add several records with the same issue number and different project IDs.

**Comment by b2z** [comment]
All good :+1:

**Comment by mbabker** [comment]
11 issues failed the unique key index when this change was made on the live database.  Wow...

**Comment by b2z** [comment]
Well that means we have some issues in our code. Do you have an info where does it happen?

**Comment by mbabker** [comment]
Not a clue.

**Comment by b2z** [comment]
Sad... Is it on cron job right? May be we need to add more logging there.

**Comment by mbabker** [comment]
The webhooks are received and processed in real-time.  The cron jobs just make sure we stay in sync for changes that don't have hooks.  I think the insert issue is probably coming from the hooks, I just have nothing to support that yet.  I can probably rotate out all the logs on the server and enable the database logger, but that one writes every recorded query and I think causes us to hit our hard drive space limits in 5-7 days (in addition to the other loggers).

**Pull request merged**
