### PR TITLE
Ensure that modified date is always set from GitHub

### PR DESCRIPTION
**Pull request by elkuku**
I believe that this might solve several issues we have currently including #607, #611, #617 and maybe others...

I started thinking about it here: https://github.com/joomla/jissues/pull/595#issuecomment-70272396

### CODE REVIEW

**Comment by mbabker** [comment]
Let's see what happens...

**Comment by elkuku** [comment]
> Let's see what happens...

:stuck_out_tongue_winking_eye:

**Comment by elkuku** [comment]
Ah.. I believe the cron for the CMS might fail on the first run since all issues have to be fetched...
But if you check the table, the modified dates for the successfully processed items should be correct, so the next run should complete... let's see :wink:

**Comment by mbabker** [comment]
I'll give it a couple hours to run through.  There are still just over 1800 records with a modified date of today in the database, so that should drop drastically as things sync up.

**Comment by mbabker** [comment]
We're close.  5874/6000 issues in the CMS repo got processed before @jissues-bot hit the API limit.  And there are now only 78 records with a modified date of today/

**Comment by mbabker** [comment]
We really need to take a deeper look at https://developer.github.com/v3/#conditional-requests at some point.

**Comment by mbabker** [comment]
Last job ran successfully on the CMS repo.  I think we're at the point now that things are running smoothly again.  Probably will need another bot when the CMS repo gets close to 10,000 items.

**Comment by elkuku** [comment]
Since we are always fetching the whole issue list, we already have the last modified date, so I don't see where we could probably use those conditional requests...

Glad that things seems to run normal again - thanks for the updates :wink:

**Comment by mbabker** [comment]
One immediate thought is if we logged somewhere the last time the command ran for a given project, then the issues that we retrieve are only those updated since the last run.

**Pull request merged**
