### PR TITLE
Activity charts

### PR DESCRIPTION
**Pull request by mbabker**
This branch starts working on implementing activity charts in the site to replace those that used to be on developer.joomla.org.  Still a long way to go, but this chart does render the data it's pulling correctly.

TODO list:
 - [x] Test points aren't logged properly
 - [x] Using the GitHub username versus the user's real name
 - [ ] Layout isn't optimized to the container width
 - [ ] Most charts from https://developer.joomla.org/tracker/volunteer-activity.html (all of the component code is available at https://github.com/mbabker/bug-squad-stuff/tree/master/components/com_trackerstats)
    - [x] Individual Statistics (Tracker Points)
    - [ ] Total Project Activity (Total Tracker Points)
    - [x] Issues Open/Closed Over Time (Open/Fixed/Closed)
    - [x] Issues Open By Status
 - [ ] Frontend UI to manage points
 - [ ] Other optimizations or improvements based on feedback

@dextercowley if you have any suggestions or improvements you'd like to offer, I know I'd greatly appreciate the help.

### CODE REVIEW

**Comment by elkuku** [comment]
I'm pretty sure people would love if we implement this somehow.

**Comment by mbabker** [comment]
And nothing's changed status wise since the last time I committed stuff here.  The one chart that's in place is missing the code points measurement but works fine otherwise (I've had the new table in the live database since I started this branch).  Other charts haven't been started on yet (too much to do and not enough hours in the day), but for the most part the query structures should be very similar just needing the table and column names matched to the issue tracker database then a filter based on the chosen project.

If there's any takers, I can hook someone up with a backup of the dev site before the refactored com_code was implemented where the charts would work with a couple of code tweaks (there are some places where there's a hardcoded 12-month maximum timeframe and we're about at that 12-month mark).

**Comment by elkuku** [comment]
> too much to do and not enough hours in the day

This wasn't meant to force you to anything since from what I can see you are doing **a lot** of Joomla! related activity - big THANKS here :wink: 

What if we just merge it in so we (or others) can improve on your work done so far?

**Comment by brianteeman** [comment]
Something is better than nothing :-)

**Comment by mbabker** [comment]
I finally made a little time to start getting code points back onto the first chart.  Standalone the subquery is collecting the right data but it needs some tweaking to be used in the main query as it's returning some highly bloated values (like saying @brianteeman has opened 413 pull requests in the last 12 months).  Once it reaches a point where it works, then the code points only filter will need some adjustment to function right.

**Comment by mbabker** [comment]
Also something to consider at some point is looking at a new chart rendering platform.  jqPlot is used now but has some quirks that make it less than suitable for a 2015 website (like lack of responsiveness).  Without plugging some more content onto the chart page, with the recent template refresh enabling Bootstrap's large device viewport (finally) there's a lot of dead space to cope with here.

screen shot 2015-09-07 at 10 15 01 pm

**Comment by brianteeman** [comment]
>  (like saying @brianteeman has opened 413 pull requests in the last 12 months). 

I have no problem with that ;)

**Comment by mbabker** [comment]
I like accurate data, unlike the 93% of made up statistics.

**Comment by brianteeman** [comment]
“I make up statistics 150% of the time”

**Comment by mbabker** [comment]
Well in good news I finally came back to this and I figured out the excessive code point calculations so that last part of the graph actually works correctly now.  And got that filter working too.  So I think officially this one chart is actually finished.

**Comment by mbabker** [comment]
2 of the 4 charts are imported now.  I've got the user activity stuff and the open/closed over time in place.

Considering the hard chart's done, the rest of it's gonna come together somewhat quickly.  Any help on the other tasks for this issue (especially UI related) is definitely welcome.

**Comment by roland-d** [comment]
@mbabker I have asked @designbengel to help with the design and she agreed. She will contact you. Which other tasks do you have?

**Comment by brianteeman** [comment]
great stuff!!!! glad I prompted you

On 10 March 2016 at 08:41, RolandD <notifications@github.com> wrote:

> @mbabker <https://github.com/mbabker> I have asked @designbengel
> <https://github.com/designbengel> to help with the design and she agreed.
> She will contact you. Which other tasks do you have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194737305>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Just ping me when I need to switch my live testing server to activityChart branch to see the work online.

**Comment by mbabker** [comment]
The main tasks for the charts frontend UI is basically making the pages look like someone other than me put them together :laughing: 

For admin if we ever want to have the points configurable without directly manipulating the database we'll eventually want something that can edit those values, but that's a much lesser priority than just getting the charts published.

screencapture-local-issues-joomla-org-activity-user-joomla-cms-1457623143930

That screenshot is off my external monitor running 1080p.  Right now the page content is ONLY a single chart.  I also commented at https://github.com/joomla/jissues/pull/491#issuecomment-138410326 that I think we probably need a different chart solution but I don't really know how much effort that'll be.  When these were on the developer site they were at the same width but the pages all had modules surrounding it, we don't exactly have that type of content here.

**Comment by mbabker** [comment]
@b2z If you want to switch your server over, feel free.  The branch is in sync with master (mostly, I don't think I merged the pager commit in) so everything should be fine.

**Comment by brianteeman** [comment]
Can we make them live while waiting for improved styling?

On 10 March 2016 at 15:27, Michael Babker <notifications@github.com> wrote:

> @b2z <https://github.com/b2z> If you want to switch your server over,
> feel free. The branch is in sync with master (mostly, I don't think I
> merged the pager commit in) so everything should be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194904746>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
Ok will do it later today and let you know :wink:

**Comment by mbabker** [comment]
@brianteeman They're there.  On the projects page there's a link for each project's charts and on the top menu there's a link for the active project's charts in the Project dropdown.

**Comment by brianteeman** [comment]
Great

On 10 March 2016 at 15:36, Michael Babker <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> They're there. On the
> projects page there's a link for each project's charts and on the top menu
> there's a link for the active project's charts in the Project dropdown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194907783>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Looks like there is an occasional error where the username doesnt load and
the row number is displayed instead
Setting it to show just code for the last 7 days and then refreshing i got
different usernames to be displayed or not

On 10 March 2016 at 15:39, Brian Teeman <brian@teeman.net> wrote:

> Great
>
> On 10 March 2016 at 15:36, Michael Babker <notifications@github.com>
> wrote:
>
>> @brianteeman <https://github.com/brianteeman> They're there. On the
>> projects page there's a link for each project's charts and on the top menu
>> there's a link for the active project's charts in the Project dropdown.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/jissues/pull/491#issuecomment-194907783>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
Ya that whole code point filter is one tricky beast to get right because it's not relying on native activity in our activities table but relies on complex subqueries and joins.  It'd almost be easier to go through our activities table and change the "open" event to "open_issue" and "open_pr" as really that measure is just whether someone opened a pull request.

Of course I'm also welcome to help from someone with more experience on highly complex database transactions here too.  Maybe I'm just missing something obvious.

**Comment by brianteeman** [comment]
it's weird that sometimes it gets the username and sometimes it doesnt

On 10 March 2016 at 15:50, Michael Babker <notifications@github.com> wrote:

> Ya that whole code point filter is one tricky beast to get right because
> it's not relying on native activity in our activities table but relies on
> complex subqueries and joins. It'd almost be easier to go through our
> activities table and change the "open" event to "open_issue" and "open_pr"
> as really that measure is just whether someone opened a pull request.
>
> Of course I'm also welcome to help from someone with more experience on
> highly complex database transactions here too. Maybe I'm just missing
> something obvious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194916779>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
I haven't seen it come up with the other two filters (or it has and I've just missed it), so I'm fairly sure that issue ties into either how the subquery join is run or how I'm manually creating an ordering for that filter.

**Comment by brianteeman** [comment]
yeah i've only seen it on the code filter

On 10 March 2016 at 16:14, Michael Babker <notifications@github.com> wrote:

> I haven't seen it come up with the other two filters (or it has and I've
> just missed it), so I'm fairly sure that issue ties into either how the
> subquery join is run or how I'm manually creating an ordering for that
> filter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194930244>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Correcction I can see it on the ALL filter as well if I set a custom date of
2012-04-01 to 2012-06-01

On 10 March 2016 at 16:29, Brian Teeman <brian@teeman.net> wrote:

> yeah i've only seen it on the code filter
>
> On 10 March 2016 at 16:14, Michael Babker <notifications@github.com>
> wrote:
>
>> I haven't seen it come up with the other two filters (or it has and I've
>> just missed it), so I'm fairly sure that issue ties into either how the
>> subquery join is run or how I'm manually creating an ordering for that
>> filter.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/jissues/pull/491#issuecomment-194930244>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
We don't have the user reference for those items.  I added the user ID into the query and ran it off Sequel Pro with that date filter...

screen shot 2016-03-10 at 11 41 50 am

**Comment by brianteeman** [comment]
That explains that then ;)

On 10 March 2016 at 16:43, Michael Babker <notifications@github.com> wrote:

> We don't have the user reference for those items. I added the user ID into
> the query and ran it off Sequel Pro with that date filter...
>
> [image: screen shot 2016-03-10 at 11 41 50 am]
> <https://cloud.githubusercontent.com/assets/368545/13676772/2809d480-e6b5-11e5-9392-54a368b11e9b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194943315>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
OK, improved the name part of that query a bit to show the username associated with the activity row if a user record doesn't exist.  So at least we've got some kind of identifying name again.

**Comment by brianteeman** [comment]
That looks much better
BTW how far back does the data go?

On 10 March 2016 at 16:49, Michael Babker <notifications@github.com> wrote:

> OK, improved the name part of that query a bit to show the username
> associated with the activity row if a user record doesn't exist. So at
> least we've got some kind of identifying name again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/491#issuecomment-194948144>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
For each project it's based on its entire GitHub history.  For the CMS that'd be late 2011 when the first GitHub items were submitted.  The tracker late 2012, patch tester mid-2013, and weblinks mid-2014.

**Comment by b2z** [comment]
Well I've switched my test site, but there are no users on it, so stats are useless :(

**Comment by designbengel** [comment]
Hi there, i´ll try to deliver something at saturday :)

**Comment by mbabker** [comment]
The only metric left to do is the code points for the total activity chart.  Otherwise, all the charts are imported now.

**Comment by designbengel** [comment]
??? 
charts

**Comment by mbabker** [comment]
That could work.

**Comment by mbabker** [comment]
I've got the master branch deployed again so the charts are temporarily gone.  As soon as I get the branch sync'd back up with the asset restructure I'll push them back online.

**Comment by mbabker** [comment]
Everything's pieced back together and updated with the other app changes.  Charts are back up.

**Comment by mbabker** [comment]
Since this has been effectively deployed for some time I'm just gonna merge this to master and open another issue with the TODO list to work out the remaining improvements.

**Pull request merged**
