### PR TITLE
Use models in web hooks

### PR DESCRIPTION
**Pull request by mbabker**
Still a work in progress, this branch will have the web hooks updated to insert data to the database via model classes versus the table classes.

### CODE REVIEW

**Comment by mbabker** [comment]
OK, I think this should be ready for review now.

**Comment by b2z** [comment]
@mbabker looks good, but I wonder should we process the milestones in the hooks like we do it for labels?

**Comment by mbabker** [comment]
Probably.  But that'd be a separate PR I think to add that functionality.  This just cleans things up a bit so that the hooks are validating data with the same rules as the UI input.

**Comment by b2z** [comment]
Ok then. Let's merge and watch for it :)

**Pull request merged**
