### PR TITLE
Stop sending 'PR has new commits' comment

### PR DESCRIPTION
**Pull request by mbabker**
GitHub has started sending email notifications for commit activity on pull requests.  IMO it kinda invalidates our need for the bot to comment on PRs in this state, so this PR removes that functionality.

Thoughts?

### CODE REVIEW

**Comment by zero-24** [comment]
Hmm. I have not noticed that behavior? But if github will do this I agree with you.

**Comment by mbabker** [comment]
You have to already be subscribed to an issue for it to work.  So their notifications are targeted more specifically whereas the comment notification goes to everyone.

**Comment by mbabker** [comment]
Example:

screen shot 2016-07-02 at 2 18 10 pm

**Comment by zero-24** [comment]
:+1:

**Comment by zero-24** [comment]
Is there any reason to not merge This?

**Comment by b2z** [comment]
Code review ok, but `This branch has conflicts that must be resolved`

**Comment by zero-24** [comment]
And now we have travis errors ;)

```
FILE: /home/travis/build/joomla/jissues/cli/tracker.php
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 119 | WARNING | Line exceeds 150 characters; contains 151 characters
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by mbabker** [comment]
Exists in master, not unique here.

**Comment by zero-24** [comment]
PR is here: https://github.com/joomla/jissues/pull/836

**Pull request merged**
