### PR TITLE
Add the target branch to the title for pull requests

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Add the target branch to the title for pull requests

#### Testing Instructions

Create a PR check that the target branch has been added to the title

#### Other notices

We might want to remove the joomlacode id generation from that method? Or do you want to keep that legacy still here in that method?

### CODE REVIEW

**Comment by mbabker** [comment]
👎 this is what the `PR-*` labels are for.

**Comment by zero-24** [comment]
Sure. But you can't see the PR-* labels anywhere (e.g. mail or the notification overview) and currently it is a manual task to add that info to the title that can easily be automated.

The PR-* labels are great to filter on for sure, so i would propose to keep both.

**Comment by mbabker** [comment]
I don't see why the issue and pull request titles need version numbers in them to be honest.  Someone triaging the tracker can easily add the appropriate labels to everything, which means the only place you're missing that meta information is in your email notifications or with com_patchtester.

Not to mention, this is a very slippery slope to try and consistently implement.  You need to make sure the text is not already there, then if someone changes the base branch of a pull request you need to make sure the text correctly changes.  IMO, if someone is really adamant about having versions in titles, they can manually take the time to do it but I don't think this should be an automated action by any means (or information that really belongs in the title).

**Comment by zero-24** [comment]
Ok. Closing

**Pull request closed without merging**
