### PR TITLE
Categories per component

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/joomla/jissues/issues/894
#### Summary of Changes

Categories per component
#### Testing Instructions

Apply this patch and send a PR that changes any files e.g. `components/com_ajax/index.php`

### CODE REVIEW

**Comment by zero-24** [comment]
@b2z can you try to push this to your test server?

**Comment by b2z** [comment]
@zero-24 I can do it only on weekend cause I am living tomorrow for 3 days.

**Comment by zero-24** [comment]
No problem this is also not 100% ready yet. I hope i can make this final until the weekend :)

**Comment by zero-24** [comment]
@mbabker @b2z can you take a final review it should be good to go now? The nightly build don't start for any reason.. please reboot travis.

**Comment by b2z** [comment]
@zero-24 seems like ok. I will try to update my server today and will test :)

**Comment by b2z** [comment]
@zero-24 test server is on your branch now ;)

**Comment by zero-24** [comment]
@b2z do you have imported the last catategories too?


@mbabker send me this SQL after i have added the cats in the GUI ;)
```
INSERT INTO `#__issues_categories` (`id`, `project_id`, `title`, `alias`, `color`)
VALUES
	(41, 1, 'com_ajax', 'com_ajax', 'fbca04'),
	(42, 1, 'com_admin', 'com_admin', 'fbca04'),
	(43, 1, 'com_banners', 'com_banners', 'fbca04'),
	(44, 1, 'com_cache', 'com_cache', 'fbca04'),
	(45, 1, 'com_categories', 'com_categories', 'fbca04'),
	(46, 1, 'com_checkin', 'com_checkin', 'fbca04'),
	(47, 1, 'com_config', 'com_config', 'fbca04'),
	(48, 1, 'com_contact', 'com_contact', 'fbca04'),
	(49, 1, 'com_content', 'com_content', 'fbca04'),
	(50, 1, 'com_contenthistory', 'com_contenthistory', 'fbca04'),
	(51, 1, 'com_cpanel', 'com_cpanel', 'fbca04'),
	(52, 1, 'com_finder', 'com_finder', 'fbca04'),
	(53, 1, 'com_installer', 'com_installer', 'fbca04'),
	(54, 1, 'com_joomlaupdate', 'com_joomlaupdate', 'fbca04'),
	(55, 1, 'com_languages', 'com_languages', 'fbca04'),
	(56, 1, 'com_login', 'com_login', 'fbca04'),
	(58, 1, 'com_menus', 'com_menus', 'fbca04'),
	(59, 1, 'com_messages', 'com_messages', 'fbca04'),
	(60, 1, 'com_modules', 'com_modules', 'fbca04'),
	(61, 1, 'com_newsfeeds', 'com_newsfeeds', 'fbca04'),
	(62, 1, 'com_plugins', 'com_plugins', 'fbca04'),
	(63, 1, 'com_postinstall', 'com_postinstall', 'fbca04'),
	(64, 1, 'com_redirect', 'com_redirect', 'fbca04'),
	(65, 1, 'com_search', 'com_search', 'fbca04'),
	(67, 1, 'com_templates', 'com_templates', 'fbca04'),
	(68, 1, 'com_users', 'com_users', 'fbca04'),
	(69, 1, 'com_mailto', 'com_mailto', 'fbca04'),
	(70, 1, 'com_wrapper', 'com_wrapper', 'fbca04');
```

**Comment by zero-24** [comment]
btw do we need too add the SQL also in the install SQL @mbabker ?

**Comment by b2z** [comment]
> @b2z do you have imported the last catategories too?

Nope :(  I will later today. Will ping you!

**Comment by zero-24** [comment]
:+1:

**Comment by b2z** [comment]
Imported to http://jtracker.j4devs.ru/tracker/jissues-test

**Comment by b2z** [comment]
Well, my 2 test PRs worked as expected :+1: 
@mbabker please review and merge :)

**Comment by zero-24** [comment]
:+1:

**Pull request merged**
