### PR TITLE
Add "No code attached yet" label for CMS issues. Fix #590.

### LINKED ISSUE #590: Jissues bot - no code attached yet
If an issue is created directly on github then the bot runs and the label `No Code attached Yet` is applied
But If an issue is created directly on Jissues then the bot does not run and the label is not applied even though the issue is created on github but by JIssues and not the end user

I have just manually applied the No Code attached Yet` label

### PR DESCRIPTION
**Pull request by b2z**
See #590 for reference.

### CODE REVIEW

**Comment by b2z** [comment]
@mbabker did you miss it or you think that it is wrong implementation?

**Comment by elkuku** [comment]
I have not tested this in any way, but from what I can remember this code will not be executed if the issue is added by the hook controller thingy aka created on GitHub, or am I wrong here?

**Comment by b2z** [comment]
You are right. Then may be the right place for adding this label would be [JoomlacmsIssuesListener](https://github.com/joomla/jissues/blob/master/src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php#L57)?

**Comment by mbabker** [comment]
That listener adds the label already for issues created on GitHub.  The label isn't added for issues created in the application.

**Comment by b2z** [comment]
Why we can not use it to create the same label for CMS tracker?

**Comment by mbabker** [comment]
Because the listeners aren't in use in the main controllers right now, they're only registered to the webhooks.

**Comment by b2z** [comment]
Right... So when an issue is created on GitHub this listener adds `no code` label back on GitHub. When issue is created in the application this listener does not run, then my commit is ok? :smile:

**Comment by mbabker** [comment]
It's an ugly workaround but it would work.  We really need to work on #596...

**Comment by b2z** [comment]
> It's an ugly workaround but it would work. 

I know :(

**Pull request merged**
