### PR TITLE
Test results UI improvement. Close #716

### LINKED ISSUE #716: staying on the same screen after submitting a test result
after submitting a result by clicking "Submit test result", the secreen remains the same and therefore suggests that the submission didn't proceeded.
This must explain the fact that for some tests, we can see 4 results submitted.
thanks
(screenshot is the screen after having submitted a test result)
sans titre2

### PR DESCRIPTION
**Pull request by b2z**
This PR will improve UI on test result submit.

Tests are welcomed :)
http://jissues.j4devs.ru/tracker/jissues-test

### CODE REVIEW

**Comment by zero-24** [comment]
Works great. Thanks. But I'm not 100% sure if we should hide it also for the alter test button.

**Comment by b2z** [comment]
> Works great. Thanks. But I'm not 100% sure if we should hide it also for the alter test button.

So what's the final decision? :)

**Comment by zero-24** [comment]
>So what's the final decision? :)

Don't do it for alter test but for "test this" :smile:

**Comment by b2z** [comment]
> Don't do it for alter test but for "test this" 

Done ;)

**Comment by zero-24** [comment]
:+1: Just one more place (on the edit site) needs the fix for the test this button as well :+1:

**Comment by b2z** [comment]
Sorry for the delay. Added improvement to edit screen and also fixed some founded bugs.
http://jissues.j4devs.ru/tracker/jissues-test

@mbabker or @elkuku will you review please?

**Pull request merged**
