### PR TITLE
Implement the first httpheader for the issue tracker

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

With this PR we set the basic http security headers

#### Open points / questions

- [ ] CSP rules (needs to wait until we have a csp-reporter place)

### CODE REVIEW

**Comment by mbabker** [comment]
Umm, this isn't the help proxy, and I'm not aware of anyone iframing the issue tracker into a site 😉

**Comment by Hutchy68** [comment]
Ooops, watching football previews. 😞 Thought it was a blanket default for all sites.

**Comment by mbabker** [comment]
Well, it probably is a default, but that's why we have PR reviews and repositories for the majority of the sites.  Go back to football now.

**Comment by Hutchy68** [comment]
✅  🏈 + 📺 == 😀

**Comment by zero-24** [comment]
👍 Have fun with football today 😄

**Comment by zero-24** [comment]
Thanks but looks like this server has also a broken mod_headers module: https://securityheaders.io/?q=https%3A%2F%2Fissues.joomla.org%2F&hide=on&followRedirects=on :(

**Comment by mbabker** [comment]
`developer.`, `framework.`, and `issues.` all reside on the same server.

**Pull request merged**
