### PR TITLE
Support new GitHub webhook events (Ref #776)

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #776

#### Summary of Changes

Supports new GitHub webhooks for editing of issue, PR, and comment contents and deleting comments

For issues and pull requests, when the `edited` webhook action is triggered a slimmed down version of our update process will run which specifically only grabs the edited fields and logs an edited activity to the table.  Truthfully not much different than our update handler is in general, but if we decide to make other changes later on (part of the reason we were always updating the title/body on all events is because of the lack of this webhook action) it's not too difficult.

For comments, when the `edited` webhook action is triggered the comment's contents should be updated (no other changes happen in the database; in the UI we may consider adding an edited comment similar to how GitHub displays them).  When the `deleted` webhook action is triggered the corresponding activity record is deleted.

#### Testing Instructions

Have a repository push issue, pull request, and issue/PR comment webhooks to an install of the tracker and ensure the events are processed.

### CODE REVIEW

**Comment by b2z** [comment]
After we will merge #770 I will update my testing server and will test this PR properly.

**Comment by elkuku** [comment]
> After we will merge #770 I will update my testing server and will test this PR properly.

@b2z Do you still want to test this on your server or should we test it "live"?

Code looks good :wink:

**Comment by b2z** [comment]
I prefer to test it before merge. There is no rush ;) I will update today to this PR.

**Comment by b2z** [comment]
Strange, but when I checkout this branch I have an error:

> [2016-07-22 22:29:04] JTracker.CRITICAL: Exception of type RuntimeException thrown {"exception":"[object] (RuntimeException(code: 0): Invalid renderer: twig at /home/j4devs/domains/jtracker.j4devs.ru/jissues/src/JTracker/Controller/AbstractTrackerController.php:373)"} {"url":"/","ip":"89.201.107.175","http_method":"GET","server":"jtracker.j4devs.
> ru","referrer":null}

And a white page saying 

> Class 'Joomla\View\Renderer\Twig' not found

**Comment by mbabker** [comment]
Probably because the branch hasn't been updated in a while and very far behind current Composer install.  master branch is merged now, so it should be good.

**Comment by b2z** [comment]
Yeap it's working now. Testing.

**Comment by b2z** [comment]
Comments are working good - edited & deleted. But issues and PRs are not - editing on GitHub does not sync with tracker. Payloads are showing `200 OK` response.
https://github.com/b2z/jissues-test/pull/46
http://jtracker.j4devs.ru/tracker/jissues-test/46

**Comment by mbabker** [comment]
Now try it.

**Comment by b2z** [comment]
Now content is updating, but another issue is here - along with that labels and milestones are being deleted :confused: 
https://github.com/b2z/jissues-test/issues/8
http://jtracker.j4devs.ru/tracker/jissues-test/8#event-4806

**Comment by mbabker** [comment]
That's a bad sign, anywho hopefully those aren't lost now.

**Comment by b2z** [comment]
Now :+1:

**Comment by elkuku** [comment]
Glad someone has tested this... thanks @b2z

**Pull request merged**
