### PR TITLE
Fix #584 - permalink button

### LINKED ISSUE #584: Permalink button don't work with more than one selection
#### Steps to reproduce the issue

- access: http://issues.joomla.org/tracker/joomla-cms
- filter per category `Router / SEF`
- and filter per User `Hackwar`
- try the permalink button

#### Expected result

screen shot 2014-12-28 at 18 12 55

All PRs that match to both conditions get displayed (as we have if we select it manually)

#### Actual result

screen shot 2014-12-28 at 18 12 47

All PRs by the user get displayed.

### PR DESCRIPTION
**Pull request by b2z**
This PR will replace non alpha numeric characters in category name from the categories filter and will allow permalink button to work correctly.

But to make it work all aliases of the categories should be named (renamed) using the common pattern:
1. Spaces and non alpha numeric characters should be replaced with dash. 
2. Short names are not allowed

For example:
```
Router / Sef - router-sef
External Library - external-library
Language & Strings - language-strings
Templates (admin) - templates-admin
```

Also this PR will add `created_by` to permalink button.

As always you are welcome to test it on my [JIssues test website](http://jtracker.j4devs.ru/tracker/jtests)

### CODE REVIEW

**Comment by zero-24** [comment]
thanks @b2z

One smal issue with this here. The `filter-sort` is not added to the permalink (Newest / Oldest / Recently updated / Least recently updated) atm it allways fallback to `Newest`

Example: http://jtracker.j4devs.ru/tracker/jtests/?status=1&user=undefined&sort=3&label=20&created_by=jtester&stools-active=1

Try to sort by `Least recently updated` and try the permalink button.

Permalink with `created_by` and category label works ok here. Good Job :+1:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/jtracker/592">issues.joomla.org/jtracker/592</a>.</sub>

**Comment by b2z** [comment]
Should be fixed now :wink:

**Comment by zero-24** [comment]
thanks @b2z fixed now!

**Comment by b2z** [comment]
Waiting for merge now :octocat:

**Comment by b2z** [comment]
Since it is merged I have updated all aliases of categories in the CMS project to match the pattern.

**Pull request merged**
