### PR TITLE
Add milestones filter. Close #723.

### LINKED ISSUE #723: Add an filter for milestones with the search tools
Can we have a filter on milestone on the search tools?

### PR DESCRIPTION
**Pull request by b2z**
Pull Request for Issue # 723.

#### Summary of Changes
Added milestones filter to issues filter bar and moved the filter bar to separate template.

#### Testing Instructions
Check that milestones filter is working correctly and other filters did not break.
You can test on my [testing server](http://jtracker.j4devs.ru/tracker/joomla-cms).

### CODE REVIEW

**Comment by zero-24** [comment]
:+1: Looks good here :)

**Comment by mbabker** [comment]
My one suggestion would be to sort the milestones in order, otherwise looks fine.

**Comment by b2z** [comment]
@mbabker currently [getMilestones()](https://github.com/joomla/jissues/blob/master/src/App/Projects/TrackerProject.php#L365) is ordered by `milestone_number`. What do you suggest?

**Comment by mbabker** [comment]
The title if practical.  One of the screens I looked at the filters were in
a "funny" order (not quite this but it felt something like 3.3.6, 2.5.28,
3.4.0, 3.5.0, 3.4.1)

**Comment by b2z** [comment]
Updated - now milestones are ordered by title ;)

**Comment by mbabker** [comment]
It still puts the open milestones before the closed ones.  But honestly I'm OK with this.

**Comment by b2z** [comment]
We could add order by `state DESC` ?

**Comment by mbabker** [comment]
Nah, it's fine how it is now.

**Pull request merged**
