### PR TITLE
First pass on PHP 7 bump

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Upgrades some of the architecture for PHP 7, including:

- Wrapping the front controllers in JavaScript like IIFE functions, this prevents variables used in these files from leaking into the rest of the app as global variables (https://www.bram.us/2015/01/02/php-7-iife-support/ briefly covers this feature)
- Bumps PHPUnit to 6.0
- Bumps Symfony dependencies to the 3.x branch
- Bumps Twig to 2.0
- General vendor update
    - joomla/database to 1.5 (we can start using prepared statements now)
    - joomla/view is locked to the last commit before the package's dependency to joomla/model is refactored out

#### Testing Instructions

The app still works

### CODE REVIEW

**Comment by elkuku** [comment]
I have tested this and everything seems to work :wink:

**Comment by b2z** [comment]
Just reinstalled [my testing server ](http://jtracker.j4devs.ru/tracker/jtracker-tests)- running fine 👍

**Comment by elkuku** [comment]
The Travis build for PHP nightly is failing. I have no idea why phpcs would
spit out those errors on PHP 7.2 only #confusion ...

Am 17.02.2017 1:56 nachm. schrieb "Dmitry Rekun" <notifications@github.com>:

**Comment by zero-24** [comment]
Where is phpcs failing @elkuku ?

**Comment by elkuku** [comment]
@zero-24: It looks like [this](https://travis-ci.org/joomla/jissues/jobs/202675127#L328)

**Comment by zero-24** [comment]
please take a look here #948 @elkuku

**Pull request merged**
