### PR TITLE
Refactor JoomlacmsPullsListener::checkFilesAndAssignCategory() method

### PR DESCRIPTION
**Pull request by elkuku**
#### Summary of Changes

* Refactor JoomlacmsPullsListener::checkFilesAndAssignCategory()
* Add a unit test for this method

#### Testing Instructions
Check if all files are correct for the corresponding category.
I believe that there are some inconsistencies.
Have a look at the unit test and see if the categories corresponding to the file/path are correct.

**Note** Unit test are failing if executed from within the jtracker script. If they run "standalone" they produce no errors.

@mbabker I'm almost sure that you have a solution to the error:
`ERROR: Serialization of 'Closure' is not allowed`
that appears here: https://travis-ci.org/joomla/jissues/jobs/146807076
Note that unit test run again here with no errors...

### CODE REVIEW

**Comment by mbabker** [comment]
You need [this declaration](https://github.com/joomla/jissues/blob/master/tests/tracker/Helper/IpHelperTest.php#L20-L26) in the test classes.  The issue is that our front controllers (www/index.php and cli/tracker.php) leave variables in global scope (the DI container and path to the autoload.php file in both; the Composer autoloader instance in CLI; and the web application instance for the web requests), so when PHPUnit tries to save state and serialize the globals those variables are included in it and the container can't be serialized when it has Closures within it.

One thing that could help with that is [using an IIFE in the front controllers](http://stackoverflow.com/questions/35044452/iife-immediately-invoked-function-expression-in-php) which would cause those variables to not be globally scoped anymore.

**Comment by elkuku** [comment]
Not sure if a simple "Thanks" will be enough, but if I buy you a beer instead you might get an alcoholic pretty soon :wink: 

Actually I had the declaration right [here](https://github.com/joomla/jissues/pull/847/commits/d677c24f333870b47670be21847f3451985a5b83#diff-63884b52eb32d0065c342b37bf2c0812R28) but since I also set `$runTestInSeparateProcess = true;` it didn't work (only changed the error message...)

The "IIFE" thing looks scary to me at first glance (in PHP) - have to get my head around it...

well, Thank you Michael!

**Comment by mbabker** [comment]
The "IIFE" thing is pretty similar to JavaScript, https://github.com/joomla/jissues/blob/master/www/media/js/jtracker.js is exactly that 😉 

At a glance this all looks fine.

**Comment by elkuku** [comment]
@zero-24 could you take a look at this?
Especially the definitions [here](https://github.com/joomla/jissues/blob/1eeaacc91bbc85a64b6f1fc3d26d85f2ee0c01f7/tests/tracker/Hooks/Listeners/JoomlaCmsPullsListenerCheckFilesAndAssignCategoryTest.php#L54-L100)
and also the unit test [here](https://github.com/joomla/jissues/blob/1eeaacc91bbc85a64b6f1fc3d26d85f2ee0c01f7/tests/tracker/Hooks/Listeners/JoomlaCmsPullsListenerCheckFilesAndAssignCategoryTest.php#L54-L100)
and see if it's understandable and maintainable?

**Comment by zero-24** [comment]
Looks good. Maybe we can add some more Information to the dock block?

**Comment by elkuku** [comment]
Makes sense - I added some words.

Any suggestions are welcome :wink:

**Comment by mbabker** [comment]
So I sync'd this up with master and I also added matches for the PostgreSQL and SQL Server database classes to those categories (with test cases).  At a glance things look good to go here for me.

**Pull request merged**
