### PR TITLE
Add deleting of comments that was deleted on GitHub. Ref #586

### PR DESCRIPTION
**Pull request by b2z**
This will fix the issue when comments deleted on GitHub are not deleted on tracker. Ref #586

### CODE REVIEW

**Comment by elkuku** [comment]
Yeah this seems to work :wink:

**Comment by elkuku** [comment]
While testing this, I discovered a "thingy" that causes all issues to be processed when our CLI script runs...
https://github.com/joomla/jissues/commit/04d2943dc0f95b0ecc2876f12272d83f0f844892
This has been modified multiple times to fix one bug after another and currently the last modified date is always overwritten...
`@todo`....

**Comment by b2z** [comment]
Can you look also on this PR please #592

**Comment by b2z** [comment]
> While testing this, I discovered a "thingy" that causes all issues to be processed when our CLI script runs...

Hmm... How to avoid it? CLI and not CLI are using the same class. Should we pass some kind of parameter or flag to determine who is acting?

**Comment by elkuku** [comment]
> Should we pass some kind of parameter or flag to determine who is acting?

I think we should not set the last_modified_date in the store method at all... Do you remember the places where it is used by "non CLI" code?...

**Comment by b2z** [comment]
Exactly not, but think that in issue add, save and edit.

**Comment by elkuku** [comment]
@allenzhao added a commit message stating a fix of a modified_date bug in https://github.com/joomla/jissues/commit/dfbb4a5fd2e7c87943beac10f87b0560030d19d9 when he added a check for a db null date but I can't remember what that bug was :(

**Comment by elkuku** [comment]
Also... I feel like something wrong happens here: https://github.com/joomla/jissues/issues/427

**Comment by b2z** [comment]
It seems that we have many places where modified is set :)

**Comment by elkuku** [comment]
I think we are using the last_modified_date from GitHub for issue comments and the date/time on our server for the activities, so I believe there might be a wrong time zone setting here that causes #427 - maybe...

**Comment by b2z** [comment]
Test :wink:

**Comment by b2z** [comment]
@mbabker how often does the cron job run? I've made a comment here more than one hour ago and then deleted it, but still it is [not deleted](http://issues.joomla.org/tracker/jtracker/595#event-61753) on the tracker.

**Comment by mbabker** [comment]
All I'm going to say is it helps when the code is deployed live (that commit was merged on a weekend I was traveling, forgot to sync up when I got back) :blush:

**Comment by b2z** [comment]
glad that it is working after all :tongue:

**Comment by brianteeman** [comment]
Great stuff

**Pull request merged**
