### PR TITLE
Update PHP package source. Close #987

### LINKED ISSUE #987: Vagrantbox: add support for future PHP7 versions
Dotdeb PHP packages [will support only PHP 7.0](https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/
). To ensure up to date version of PHP we need to use another packages. The author is suggesting to switch to the [PPA packages](https://packages.sury.org/php/) provided by Ondrey Sury. 

Lets update to them :) The manual for this can be found at https://www.groots.be/?p=35.

### PR DESCRIPTION
**Pull request by b2z**
Pull Request for Issue #987.

#### Summary of Changes

```
vagrant@contrib-jessie:~$ php -v
PHP 7.1.9-1+0~20170902060604.8+jessie~1.gbpebe5d6 (cli) (built: Sep  2 2017 06:21:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.9-1+0~20170902060604.8+jessie~1.gbpebe5d6, Copyright (c) 1999-2017, by Zend Technologies
with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

#### Testing Instructions

You will need to destroy your current virtual machine and create a new one by running `vagrant up`.

### CODE REVIEW

**Comment by elkuku** [comment]
I have tested this (on a windows machine) and it works as advised.

**Comment by wilsonge** [comment]
Just tested on my mac and I'm getting

```
george@ ~/Sites/jissues (master) $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jissues-debian-jessie64-v2' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'jissues-debian-jessie64-v2' (v0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/debian/boxes/contrib-jessie64/versions/8.8.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

I changed it to require a box in the usual way (i.e. not give a custom box name but give a box name of `debian/contrib-jessie64` and it downloaded the box. However then I get when loading the site

```
PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/mysqli.so' - /usr/lib/php/20160303/mysqli.so: undefined symbol: mysqlnd_global_stats
```

**Comment by b2z** [comment]
@wilsonge seems that they changes the source. Try this one:
https://app.vagrantup.com/debian/boxes/jessie64/versions/8.10.0/providers/virtualbox.box

**Comment by wilsonge** [comment]
The link works I still get the mysql error
screen shot 2018-02-17 at 19 15 20

**Comment by b2z** [comment]
Hmm, did not face it. Have you tried to destroy vagrant instance and run it again?

**Comment by wilsonge** [comment]
Multiple times :)

**Comment by b2z** [comment]
I don't get it :) I also have tried several versions (destroying the previous ones) and did not hit it :( What I hit is that Debian was not able to install some packages because of not found problem. This was solved by:
```
vagrant ssh
sudo su
apt-get update --fix-missing
```

Then run `vagrant provision`.

**Pull request merged**
