### PR TITLE
[Auto Labels] Make sure only NPM dependencies get tagged

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Make sure only external NPM dependencies get tagged as `NPM Dependency Changed`

#### Testing Instructions

- Please check: https://github.com/joomla/joomla-cms/pull/23936
- No NPM dependencies ins included in that patch.
- throw the PR against the current code and the proposed code.

### CODE REVIEW

**Comment by mbabker** [comment]
The intent wasn't to tag only vendor changes, but rather everything that relates to NPM resources.  If this is going to be an issue then the `build/media_source` directory should just be removed in full because that vendor directory has basically nothing in it in relation to what the full dependency tree is.

**Comment by zero-24** [comment]
Ok didn't know that as i would our code not call an npm dependencie but by your definition the current code here makes more sense. Closing here. Thanks 🎉

**Comment by mbabker** [comment]
Maybe the label text should change to `NPM Resource Changed` or something if "dependency" is going to be misleading.  I basically just copied the Composer label and changed "Composer" to "NPM".

**Comment by zero-24** [comment]
Yes `NPM Resource Changed` sounds good to me. Should i do an PR or would you like to directly commit it?

**Comment by mbabker** [comment]
I've changed the label on the CMS repo and committed the change in the listener here.

**Comment by zero-24** [comment]
Thanks 👍

**Pull request closed without merging**
