### PR TITLE
Exclude labeled/unlabeled events from sync. Close #655

### LINKED ISSUE #655: Labels event is duplicating
I just noticed that labels event is duplicating for some reason. For example in [6893](http://issues.joomla.org/tracker/joomla-cms/6893)

@zero-24 how do you change labels - on the tracker? Just want to replicate and fix it.

### PR DESCRIPTION
**Pull request by b2z**
Ref #655

### CODE REVIEW

**Comment by b2z** [comment]
@mbabker this should be save to merge :wink:

**Comment by b2z** [comment]
@mbabker review and merge please :wink:

**Comment by mbabker** [comment]
OK, ya, sorry.  Got busy for a few days.

**Comment by b2z** [comment]
Thanks :)

**Pull request merged**
