### PR TITLE
JoomlacmsTestsListener

### PR DESCRIPTION
**Pull request by elkuku**
This will add an `onTestAfterSubmit` event and a `JoomlacmsTestsListener` event listener that will create a status on GitHub whenever a test is submitted (or altered) on jissues.

FYI GitHub statuses are those annoying messages that appear for "external services" like Travis.

In our case this would reflect the test results (from JBS) to the GitHub UI along with the Travis (or other) test results.

Example:

usr-tests

The text that appears is fully customizable for every project and  I would beg you to postpone discussions about the wording after and only if this PR has been merged - thanks :wink: 

Depends on #694, closes #596

### CODE REVIEW

**Comment by b2z** [comment]
#694 is merged now and we can start to test listeners.

And now here is the problem:
```
PHP Fatal error:  Call to undefined method App\\Tracker\\Controller\\TestR
esult\\Ajax\\Submit::addEventListener() in /home/admin/web/jissues.j4devs.ru/jissues/src/App/Tracker/Controller/TestResult/Ajax/Submi
t.php on line 54
```

`AbstractAjaxController` extends `AbstractTrackerController` that is not aware about hooks. Funny thing is that our `AbstractHookController extends AbstractAjaxController` :smile: We need to sort out our hierarchy here :wink:

**Comment by elkuku** [comment]
This looks like changes from the `master` branch are missing - updated :wink: 

The hooks controllers are extending the base AJAX controller because of the response being in JSON notation... I also scratched my head about this after not seeing the code for a while...

**Comment by mbabker** [comment]
I changed that a while back so that when you're looking at the events in GitHub's admin console the response in there isn't a full HTML page (digging through a couple hundred lines of that to find error messages is a pain).

**Comment by elkuku** [comment]
Yes that makes sense.
TBH I wasn't even aware that GitHub stores all those responses and corresponding payloads... pretty awesome! - thanks again @github :wink:

**Comment by elkuku** [comment]
A diagram of **some** of our controller classes:
diagram

**Comment by b2z** [comment]
Works good now! The only problem is the link `Details` from Github to Tracker. When I click on it I get an error:
```
404 UnexpectedValueException
This project does not exist.
```
Testing here
https://github.com/b2z/jissues-test/pull/15

**Comment by mbabker** [comment]
The link is hardcoded to `issues.joomla.org` and that project doesn't exist on our live site :wink:

**Comment by b2z** [comment]
Oh my :) Did notice that it leads to i.j.o :) Well I think this PR is ready for merge.

**Pull request merged**
