### PR TITLE
Add the new components csp and workflow

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #1030 

#### Summary of Changes

Add the new components csp and workflow to the auto detection

Before this patch i have created the com_csp & com_workflow category in the tracker application. Do we need to include that somewhere in the repo too?

#### Testing Instructions

Create a patch that changes com_csp or com_workflow
The tracker now adds the categories

### CODE REVIEW

**Comment by zero-24** [comment]
Do we need to include that new categories somewhere in the repo too?

**Comment by mbabker** [comment]
Nope.

**Comment by zero-24** [comment]
Thanks!

**Comment by franz-wohlkoenig** [comment]
thanks @zero-24

**Pull request merged**
