### PR TITLE
Add auto category feature for the JavaScript category

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Add auto category for JS changes

#### Testing Instructions

Change a JS file (.js) => the JavaScript category should be added by the Tracker :smile:

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for adding this

**Comment by elkuku** [comment]
Looks good on code review ;)

Just a small note...
If it happens that `foobar.js.php` exists for some reason and is treated as a js file, you might finally switch to regular expressions :tongue:

**Comment by elkuku** [comment]
ARGH, and looking over it again I noticed, that 

`strpos($file->filename, '.js') === 0`

will check if the file name **starts** with `.js`

So the whole thing won't work :(

You might just write 
```php
if (preg_match('/.js$/', $file))
```

To check that the file **ends** ($) with `.js`

**Comment by elkuku** [comment]
OK I just modified that, maybe toy could take a look at a1597953c1859e30c9e9a30c60efa8c152609163 to see if that's OK?

**Comment by zero-24** [comment]
Ahh sorry @elkuku just a c&p error. Thanks.

**Comment by elkuku** [comment]
c&p is so evil...

**Pull request merged**
