### PR TITLE
Global events

### PR DESCRIPTION
**Pull request by elkuku**
This moves the event handling methods from the hooks controller to the base controller to make them available to all controllers.

<del>Adds a new event `onTestAfterSubmit`</del> - listeners <del>will follow</del> are here: #695, #696 :wink:

Currently open #596 could be implemented using events.
I believe that also the code from #667 could be done using an appropriate event instead of commenting :wink:

### CODE REVIEW

**Comment by b2z** [comment]
Now testing this branch [here](http://jissues.j4devs.ru/tracker/jissues-tests). #667 is broken :(

**Comment by elkuku** [comment]
Do you get some kind of error or does is just not work?

**Comment by b2z** [comment]
Nothing. It is just not triggered. I will try to test on master branch later today to see is it something wrong on my server or not.

**Comment by elkuku** [comment]
Hmm thinking about it I guess this is caused by the way we get the project "object" inside the hooks controllers...
I wasn't expecting anybody testing hooks with a "non joomla-cms project"...

Let me think a bit about some adjustments...

**Comment by elkuku** [comment]
OK I made some further adjustments. Could you re-sync please?

Since this resolves a `@todo` added by @mbabker, may I request a small code review on ab37def8e0bba64708eb4a92ac8a7ae6552ae9bd please?

**Comment by elkuku** [comment]
May I spam something (almost) completely unrelated here? [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) is pretty cool for crafting POST request (to debug webhooks for example). It looks like this:

2015 08 17 120721_1366x768_scrot

**Comment by b2z** [comment]
Resynced and it works now :) :+1:

**Comment by elkuku** [comment]
Fantastic :tada:

**Comment by b2z** [comment]
And what's the possible problem in code with ab37def ?

**Comment by elkuku** [comment]
The sky may fall down on us :tongue: 

No well, since it was a `@todo`, I would like to ensure that it has been properly done :wink:

**Comment by mbabker** [comment]
At a glance it seems fine.

**Pull request merged**
