### PR TITLE
Solving warning

### PR DESCRIPTION
**Pull request by avinashdaiict**

### CODE REVIEW

**Comment by avinashdaiict** [comment]
when I was testing the langfiles,I was getting repetitive " warning: header field 'Language' missing in header"
in all the pot extension files .
By this pull request these warnings have been removed.

**Comment by avinashdaiict** [comment]
@drmmr763 please review these. I have added some language header to remove the warnings

thanks

**Comment by b2z** [comment]
> when I was testing the langfiles

Where you were testing them?

**Comment by avinashdaiict** [comment]
@b2z  I am runing the tests on ubuntu
this is the way I am running them, please tell me if I am doing it wrong
avi@avi-Lenovo-B40-70:/opt/lampp/htdocs/jissues/cli$ ./tracker.php test run
------------------------------------------------------------
              Joomla! Tracker CLI Application
                         1.0.0-beta
------------------------------------------------------------
------------------------------------------------------------
                         Test Suite
------------------------------------------------------------
------------------------------------------------------------
                      Test Checkstyle
------------------------------------------------------------
............................................................  60 / 231 (26%)
............................................................ 120 / 231 (52%)
............................................................ 180 / 231 (78%)
...................................................


Success
------------------------------------------------------------
                        Test PHPUnit
------------------------------------------------------------
PHPUnit 4.4.5 by Sebastian Bergmann.

Configuration read from /opt/lampp/htdocs/jissues/phpunit.travis.xml

...........

Time: 8.1 seconds, Memory: 17.00Mb

OK (11 tests, 13 assertions)

Success
------------------------------------------------------------
                    Check language files
------------------------------------------------------------
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/ru-RU/ru-RU.Debug.po:67: a format specification for argument 1 doesn't exist in 'msgstr[0]'
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/ru-RU/ru-RU.Debug.po:75: a format specification for argument 1 doesn't exist in 'msgstr[0]'
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/ru-RU/ru-RU.Debug.po:83: a format specification for argument 1 doesn't exist in 'msgstr[0]'
msgfmt: found 3 fatal errors

 There have been errors. 

Test Suite Finished.

**Comment by avinashdaiict** [comment]
previously a lot of warning were coming related to missing of langauge header files were coming ,So I just added them(the header files).
Please guide me if I am going the wrong way .
Thanks

**Comment by elkuku** [comment]
Hi,
First if all: Welcome on board!

I also received those warnings with some (older) versions of the gettext utilities, while newer versions seem to not complain about those missing language header information (which honestly does not make that much sense since those are just template file with no specific language).

Could you please tell us some information about your system (like OS, PHP version, get text utilities version)
The versions used by our "reference systems" run without those warnings
https://travis-ci.org/joomla/jissues/jobs/51694990
Or our virtual environment based on Debian.

Also, those files are auto generated... Could you run the command ˊmake langtemplatesˊ and see what happens?

**Comment by avinashdaiict** [comment]
PHP 5.5.9
UBUNTU 14.04
gettext (GNU gettext-runtime)- 0.18.3

Yeah it may be a problem with the version of the gettext
But, even as you can see there are 3 errord still coming on my version.So should I work towards fixing them or not?
Please guide me to contribute to the community.
Thanks,
Avinash

**Comment by avinashdaiict** [comment]
@elkuku 
I run the command make langfiles and the errors had gone .
Could you please tell me how to learn more about the project ?
Thanking you,
Avinash

**Comment by b2z** [comment]
> Could you please tell me how to learn more about the project ?

What exactly do you want to know? ;)

**Comment by avinashdaiict** [comment]
@b2z 
I want to contribute more towards the project .
Please guide me accordingly about what sould I do next ?
Thanking you,
Avinash

**Comment by kshitijSharma2014** [comment]
Hi everyone,
Even I was trying to run to run tracker.php and reffered to https://travis-ci.org/joomla/jissues/jobs/51694990

all the other test like phpunit,phplock, copypaste etc are runnning successfully but this one is bothering me. I had also done executed  "make langfiles".

This is my output:
[ksharma@localhost jissues]$ bin/jtracker test langfiles
------------------------------------------------------------
              Joomla! Tracker CLI Application
                         1.0.0-beta
------------------------------------------------------------
------------------------------------------------------------
                    Check language files
------------------------------------------------------------
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.js.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.js.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.js.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/JTracker/g11n/templates/JTracker.js.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/templates/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/templates/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/templates/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/templates/JTracker/g11n/templates/JTracker.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Projects/g11n/templates/Projects.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Projects/g11n/templates/Projects.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Projects/g11n/templates/Projects.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Projects/g11n/templates/Projects.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Debug/g11n/templates/Debug.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/templates/Debug.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/templates/Debug.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Debug/g11n/templates/Debug.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/System/g11n/templates/System.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/System/g11n/templates/System.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/System/g11n/templates/System.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/System/g11n/templates/System.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Text/g11n/templates/Text.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Text/g11n/templates/Text.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Text/g11n/templates/Text.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Text/g11n/templates/Text.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Tracker/g11n/templates/Tracker.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Tracker/g11n/templates/Tracker.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Tracker/g11n/templates/Tracker.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Tracker/g11n/templates/Tracker.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Users/g11n/templates/Users.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Users/g11n/templates/Users.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Users/g11n/templates/Users.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Users/g11n/templates/Users.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/GitHub/g11n/templates/GitHub.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/GitHub/g11n/templates/GitHub.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/GitHub/g11n/templates/GitHub.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/GitHub/g11n/templates/GitHub.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Groups/g11n/templates/Groups.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Groups/g11n/templates/Groups.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Groups/g11n/templates/Groups.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Groups/g11n/templates/Groups.pot:8: warning: header field 'Language' missing in header

/opt/lampp/htdocs/jissues/src/App/Support/g11n/templates/Support.pot:8: warning: header field 'PO-Revision-Date' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Support/g11n/templates/Support.pot:8: warning: header field 'Last-Translator' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Support/g11n/templates/Support.pot:8: warning: header field 'Language-Team' still has the initial default value
/opt/lampp/htdocs/jissues/src/App/Support/g11n/templates/Support.pot:8: warning: header field 'Language' missing in header

 There have been errors.

**Comment by b2z** [comment]
@kshitijSharma2014 hello and welcome! These are just warning so we do not need to bother much about them for language files.

If you want to contribute first of all you should read the [documentation](https://github.com/joomla/jissues/tree/master/Documentation) we have. Then you can open our [current issues](https://github.com/joomla/jissues/issues) and start to fix them ;)

**Comment by b2z** [comment]
@elkuku should we close it?

**Comment by elkuku** [comment]
Actually I was thinking about merging it and see what happens (I don't expect anything special) since it seems to remove warnings on some systems while not affecting the others...

The only thing I don't completely agree with is the reference to poedit, but its a good piece of software so hey..

I believe it helps new contributors to get their system up and running so why not?

**Comment by b2z** [comment]
Why not :)

**Pull request merged**
