### PR TITLE
Add PHP 7 support to Vagrant box. Close #935.

### LINKED ISSUE #935: Update Vagrant for PHP 7
Our live server now runs PHP 7.  Before starting to make code/dependency updates for that, let's get the Vagrant file updated.

### PR DESCRIPTION
**Pull request by b2z**
Pull Request for Issue #935.

#### Summary of Changes

```
vagrant@contrib-jessie:~$ php -v
PHP 7.0.15-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.15-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies
with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

#### Testing Instructions
You will need to destroy your current virtual machine and create a new one by running `vagrant up`.

### CODE REVIEW

**Comment by b2z** [comment]
Should I provide a manual how to update our existing box to PHP 7?

**Comment by mbabker** [comment]
> Should I provide a manual how to update our existing box to PHP 7?

Is it really necessary?  I don't actually use Vagrant much so I'm not sure what all this would entail or what help it would be.

**Comment by b2z** [comment]
Dunno, just asking :) BTW what is PHP nightly Travis is not happy of?

**Comment by mbabker** [comment]
Wouldn't worry about it too much.  Basically tests against PHP's master branch.  Seems like something in PHPCS doesn't work so well with 7.2 right now.

**Comment by b2z** [comment]
Ah ok :)

**Comment by b2z** [comment]
So we are rising our requirement to PHP 7.0 or later? ;)

**Comment by mbabker** [comment]
Yep.  The server's been running it for some time, time for us to catch up.

**Pull request merged**
