### PR TITLE
Labels & milestones

### PR DESCRIPTION
**Pull request by elkuku**
This will add some more label management.

Note: It could be that there will be some "duplicate events" on the live site because I assume that changing a label will also fire a hook event - not sure.

### CODE REVIEW

**Comment by b2z** [comment]
@elkuku will you able to update this branch? I think that the current implementation is enough if nobody against?

**Comment by elkuku** [comment]
> @elkuku will you able to update this branch?

Sure, let me find some time...

**Comment by b2z** [comment]
Yeah time is luckuing currently :(

чт, 19 марта 2015, 17:11, Nikolai Plath <notifications@github.com>:

**Comment by b2z** [comment]
So I have updated the branch and improved it with the milestones. Comments are welcome :wink: 

Basically everything is working fine (I was [testing](https://github.com/jtester/tests/issues) it hard today). The only thing that concerns me is syncing of changes. See [issue 74](https://github.com/jtester/tests/issues/74) - there are many changes on the GitHub (made on my local environment), but nothing [on the tracker](http://issues.joomla.org/tracker/jtests/74) after the sync. Not sure why :(

If you need to test it live, I will provide my testing server tomorrow.

**Comment by zero-24** [comment]
@b2z 
>If you need to test it live, I will provide my testing server tomorrow.

Great i will test it if i get some time.

>Basically everything is working fine (I was testing it hard today). The only thing that concerns me is syncing of changes. See issue 74 - there are many changes on the GitHub (made on my local environment), but nothing on the tracker after the sync. Not sure why :(

Maybe as we never trigger the `#__activities` table on sync?

Can you try the following:
- create a issue with JTracker
- add the milestone and a label (with JTracker)
- see if it is synced to github
- see the activity

After this ty the following
- create a issue with JTracker
- add the milestone and a label (on Github)
- see if it is synced to jtracker
- see the activity

If the label is changed on Github it will show at the activity in jtracker (current behavior see: http://issues.joomla.org/tracker/joomla-cms/6513; Brian adds a label)

**Comment by b2z** [comment]
Do you mean JTracker on http://issues.joomla.org ? You can not add labels there...
It was everything in sync for me locally. Seems that the cron job does not sync these activities, but it should. Need to test it on my local environment also.

**Comment by b2z** [comment]
OK regarding sync, it sounds like we are not supporting these events currently - see #610. I will not implement it in this PR (want to keep it clean). That will be the next step.

**Comment by b2z** [comment]
Finally my [test server](http://jissues.j4devs.ru/tracker/jtests) is ready :) Sorry for the delay...

**Comment by zero-24** [comment]
>Finally my test server is ready :) Sorry for the delay...

Thanks @b2z !

I have just tested here.
First of all is it expected that everyone can edit and add milstones / labels? (as i can do it without in any group in your tracker?)

Some things i have notice:
- on existings the sync works good see: http://jissues.j4devs.ru/tracker/jtests/75 and https://github.com/jtester/tests/issues/75

excepted the removing of the milstone (set to non milstone)

On a new issue i open:
http://jissues.j4devs.ru/tracker/jtests/76
https://github.com/jtester/tests/issues/76

The sync don't work see the changes at JTracker and Github.

Maybe unrealted but new PRs and issues don't get synced to your tracker:
https://github.com/jtester/tests/pull/77
https://github.com/jtester/tests/issues/78

**Comment by zero-24** [comment]
A i have missed something. Also closed milestones like: Grrr11 can be assigned and will be shown:
milestone_grrr11

Is this expected?

**Comment by b2z** [comment]
> First of all is it expected that everyone can edit and add milstones / labels? (as i can do it without in any group in your tracker?)

Yes I've made it to test easier.

> On a new issue i open:
http://jissues.j4devs.ru/tracker/jtests/76
jtester/tests#76
The sync don't work see the changes at JTracker and Github.

Looks like a bug. Not sure why at the moment.

> Maybe unrealted but new PRs and issues don't get synced to your tracker:
jtester/tests#77
jtester/tests#78

They will not, because webhooks does not exist.

> Also closed milestones like: Grrr11 can be assigned and will be shown:

That's a bug. Will fix.

**Comment by b2z** [comment]
All issues are fixed.

**Comment by b2z** [comment]
Please not that GitHub => Tracker sync still will not work.

**Comment by zero-24** [comment]
Great work @b2z ! Works good here also for #76 and #81 Yery much thanks! :+1:

**Comment by b2z** [comment]
Need a code review now @mbabker @elkuku

**Comment by b2z** [comment]
Will we make it in ? ;)

**Comment by mbabker** [comment]
I'll take a look tomorrow.  Getting ready right now to head to the airport.

**Comment by b2z** [comment]
Safe flight

чт, 9 апр. 2015, 16:03, Michael Babker <notifications@github.com>:

**Comment by zero-24** [comment]
>P.S.
Currently all users with the EDIT rights (JBS and PLT) can add/edit milestones and labels. Please let me know if we should change this.

Sorry @b2z i have just notice that this question is not answered and I'm not sure if we should give all JBS members access to the milestones and labels.

I think the idea of the `CMS Maintainer` (like: https://github.com/joomla/jissues/issues/268) is a good one for the task? So this Group and also PLT can do the changes.

**Comment by mbabker** [comment]
Well that's just adding a new ACL role for the tracker then.  That wouldn't change the underlying code.

**Comment by b2z** [comment]
@mbabker actually you are not correct. For this we should add new ACL action like `edit.something`, because we authorize against actions and not roles.

**Comment by mbabker** [comment]
Err... Ya, I just realized it.  Even if we added that maintainer group, they'd still have the same edit permission as JBS.  So it would need a new action.

**Comment by b2z** [comment]
The question is - should we wait for more coding on adding action or merge it as it is. Then these people will have access to this feature:
```
    MAT978
    vdespa
    drmmr763
    SniperSister
    Hackwar
    infograf768
    gwsdesk
    pjwiseman
    zero-24
    Harmageddon
    roland-d
    nibra
    topwebs
    rvbgnu
    gunjanpatel
    anupkumarmishra
    mrunalpittalia
```

Of course I will add an additional action, but not now. Desperately lucking free time these days.

**Comment by zero-24** [comment]
@b2z is it difficult to limit it for PLT until we have the CMS Maintainer Group for now?

**Comment by zero-24** [comment]
If you tell me what needs to be done i can make a PR to fix it.

I guess it is only:
`{% if user.check("admin") %}`
insted of
`{% if user.check("edit") %}`

For now?

**Comment by b2z** [comment]
You are right - we can limit it to PLT checking as admin. But it's not only checking in templates. Checks also should be done in the Save controller. I will look into it today.

**Comment by b2z** [comment]
Check are added and tested. Now only users who can perform 'admin' action can change the labels / milestones.

**Comment by zero-24** [comment]
Great thanks @b2z !

**Pull request merged**
