### PR TITLE
Add request parameters to debug information

### PR DESCRIPTION
**Pull request by elkuku**
This is meant as another aid to further debug #834

### CODE REVIEW

**Comment by elkuku** [comment]
Please send a little `ping` when it's deployed :wink:

**Comment by mbabker** [comment]
As soon as my ISP gets off their lazy backside and responds to my service
request...

**Comment by elkuku** [comment]
This is just a friendly reminder :wink:

**Comment by mbabker** [comment]
Still offline.  I'm paying a bunch of idiots…

**Comment by elkuku** [comment]
LOL, ok I'll try to be patient..

**Comment by mbabker** [comment]
I just got to the office and ran the update task.  So this is deployed now.

**Comment by elkuku** [comment]
Thanks!

**Pull request merged**
