### PR TITLE
Redesign language switcher

### PR DESCRIPTION
**Pull request by b2z**
See #582 for reference. [Live demo](http://jtracker.j4devs.ru/) is available on my test server.

### CODE REVIEW

**Comment by mbabker** [comment]
Looks good.  One comment: Any way to use white text for the input field instead of it being black?  It's a little difficult to read on the menu bar.

**Comment by brianteeman** [comment]
Can you make the entire text "Select language" clickable - not just the
very small arrow

On 2 March 2015 at 19:17, Michael Babker <notifications@github.com> wrote:

> Looks good. One comment: Any way to use white text for the input field
> instead of it being black? It's a little difficult to read on the menu bar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/628#issuecomment-76787780>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
> Looks good. One comment: Any way to use white text for the input field instead of it being black? It's a little difficult to read on the menu bar.

I tried, but can not find proper CSS style to make it. We need a CSS expert here :) 

> Can you make the entire text "Select language" clickable - not just the
very small arrow

Will try

**Comment by b2z** [comment]
@brianteeman just tried to make it, but with no luck :( If I am wrapping the text in `<a>` then search is not working. I have tried to emulate with `cursor: pointer`, but it does not work. This search input is generated by the script so I can not control it... BTW you can click on the flag also, not only on the arrow.

**Comment by b2z** [comment]
Do you have any CSS expert that could help?

**Comment by elkuku** [comment]
Testing with a tablet, this works very well.

:+1:

**Comment by b2z** [comment]
Guys! I fixed both proposals with the help of @alldar. Please check it now is it ok? :wink:

**Comment by brianteeman** [comment]
It looks awesome to me

On 7 March 2015 at 09:37, Dmitry Rekun <notifications@github.com> wrote:

> Guys! I fixed both proposals with the help of @alldar
> <https://github.com/alldar>. Please check it now is it ok? [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/jissues/pull/628#issuecomment-77681451>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by b2z** [comment]
If so, can be merged :smile:  @mbabker can you look on #626 also please.

**Pull request merged**
